"""Add manual_override to Shop model

Revision ID: 145d1f98be4e
Revises: adfc954f9a8c
Create Date: 2025-07-10 10:53:07.820578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145d1f98be4e'
down_revision = 'adfc954f9a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_override', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_column('manual_override')

    # ### end Alembic commands ###
